name = "article-checker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
SENTRY_DSN = ""
SENTRY_ENVIRONMENT = "development"
SENTRY_RELEASE = "1.0.0"

[observability.logs]
enabled = true